# テキストデータの入手・変数への格納

  * 夏目漱石の「吾輩は猫である」（青空文庫）を利用
  * requestによりWebアクセス

  * bs4(Beautiful Soup)のHTML parserを利用して解析

In [ ]:
import requests, bs4

In [ ]:
response = requests.get("https://www.aozora.gr.jp/cards/000148/files/789_14547.html")

In [ ]:
soup = bs4.BeautifulSoup(response.content, "html.parser")

In [ ]:
elems = soup.select(".main_text")

In [ ]:
type(elems)

bs4.element.ResultSet

In [ ]:
texts = ''.join([elm.text for elm in elems])

In [ ]:
texts[:1000]

'\n一\n\r\n\u3000吾輩は猫である。名前はまだ無い。\r\n\u3000どこで生れたかとんと見当がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。吾輩はここで始めて人間というものを見た。しかもあとで聞くとそれは書生という人間中で一番獰悪な種族であったそうだ。この書生というのは時々我々を捕えて煮て食うという話である。しかしその当時は何という考もなかったから別段恐しいとも思わなかった。ただ彼の掌に載せられてスーと持ち上げられた時何だかフワフワした感じがあったばかりである。掌の上で少し落ちついて書生の顔を見たのがいわゆる人間というものの見始であろう。この時妙なものだと思った感じが今でも残っている。第一毛をもって装飾されべきはずの顔がつるつるしてまるで薬缶だ。その後猫にもだいぶ逢ったがこんな片輪には一度も出会わした事がない。のみならず顔の真中があまりに突起している。そうしてその穴の中から時々ぷうぷうと煙を吹く。どうも咽せぽくて実に弱った。これが人間の飲む煙草というものである事はようやくこの頃知った。\r\n\u3000この書生の掌の裏でしばらくはよい心持に坐っておったが、しばらくすると非常な速力で運転し始めた。書生が動くのか自分だけが動くのか分らないが無暗に眼が廻る。胸が悪くなる。到底助からないと思っていると、どさりと音がして眼から火が出た。それまでは記憶しているがあとは何の事やらいくら考え出そうとしても分らない。\r\n\u3000ふと気が付いて見ると書生はいない。たくさんおった兄弟が一疋も見えぬ。肝心の母親さえ姿を隠してしまった。その上今までの所とは違って無暗に明るい。眼を明いていられぬくらいだ。はてな何でも容子がおかしいと、のそのそ這い出して見ると非常に痛い。吾輩は藁の上から急に笹原の中へ棄てられたのである。\r\n\u3000ようやくの思いで笹原を這い出すと向うに大きな池がある。吾輩は池の前に坐ってどうしたらよかろうと考えて見た。別にこれという分別も出ない。しばらくして泣いたら書生がまた迎に来てくれるかと考え付いた。ニャー、ニャーと試みにやって見たが誰も来ない。そのうち池の上をさらさらと風が渡って日が暮れかかる。腹が非常に減って来た。泣きたくても声が出ない。仕方がない、何でもよいから食物のある所まであるこうと決心をしてそろ

# 前処理

* reを利用し、改行コード（\n一\n, \r\n, \n)と\u3000(全角スペース)の削除
* janomeを利用し、すべてカタカナ変換する
* jaconvを利用し、カタカナ→ひらがな変換する


In [ ]:
!pip install janome
!pip install jaconv

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 69.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for jaconv: filename=jaconv-0.3.4-py3-none-any.whl size=16416 sha256=cc66f4d53eec13ff33408bc7cf776520eb0ba201155d120dbe104e13d3d0bd94
  Stored in directory: /root/.cache/pip/wheels/46/8f/2e/a730bf1fca05b33e532d5d91dabdf406c9b718ec85b01b1b54
Successfully built jaconv


In [ ]:
import random

start_idx = int(len(texts) * random.random())
end_idx = start_idx + 1000

texts[start_idx:end_idx]

'尻の重いために破れたのではない、本人の弁解によると近頃自転車の稽古を始めて局部に比較的多くの摩擦を与えるからである。未来の細君をもって矚目された本人へ文をつけた恋の仇とは夢にも知らず、「やあ」と云って武右衛門君に軽く会釈をして椽側へ近い所へ座をしめた。\r\n「虎の鳴き声を聞いたって詰らないじゃないか」\r\n「ええ、今じゃいけません、これから方々散歩して夜十一時頃になって、上野へ行くんです」\r\n「へえ」\r\n「すると公園内の老木は森々として物凄いでしょう」\r\n「そうさな、昼間より少しは淋しいだろう」\r\n「それで何でもなるべく樹の茂った、昼でも人の通らない所を択ってあるいていると、いつの間にか紅塵万丈の都会に住んでる気はなくなって、山の中へ迷い込んだような心持ちになるに相違ないです」\r\n「そんな心持ちになってどうするんだい」\r\n「そんな心持ちになって、しばらく佇んでいるとたちまち動物園のうちで、虎が鳴くんです」\r\n「そう旨く鳴くかい」\r\n「大丈夫鳴きます。あの鳴き声は昼でも理科大学へ聞えるくらいなんですから、深夜闃寂として、四望人なく、鬼気肌に逼って、魑魅鼻を衝く際に……」\r\n「魑魅鼻を衝くとは何の事だい」\r\n「そんな事を云うじゃありませんか、怖い時に」\r\n「そうかな。あんまり聞かないようだが。それで」\r\n「それで虎が上野の老杉の葉をことごとく振い落すような勢で鳴くでしょう。物凄いでさあ」\r\n「そりゃ物凄いだろう」\r\n「どうです冒険に出掛けませんか。きっと愉快だろうと思うんです。どうしても虎の鳴き声は夜なかに聞かなくっちゃ、聞いたとはいわれないだろうと思うんです」\r\n「そうさな」と主人は武右衛門君の哀願に冷淡であるごとく、寒月君の探検にも冷淡である。\r\n\u3000この時まで黙然として虎の話を羨ましそうに聞いていた武右衛門君は主人の「そうさな」で再び自分の身の上を思い出したと見えて、「先生、僕は心配なんですが、どうしたらいいでしょう」とまた聞き返す。寒月君は不審な顔をしてこの大きな頭を見た。吾輩は思う仔細あってちょっと失敬して茶の間へ廻る。\r\n\u3000茶の間では細君がくすくす笑いながら、京焼の安茶碗に番茶を浪々と注いで、アンチモニーの茶托の上へ載せて、\r\n「雪江さん、憚りさま、これを出して来

In [ ]:
texts[:1000]

'\n一\n\r\n\u3000吾輩は猫である。名前はまだ無い。\r\n\u3000どこで生れたかとんと見当がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。吾輩はここで始めて人間というものを見た。しかもあとで聞くとそれは書生という人間中で一番獰悪な種族であったそうだ。この書生というのは時々我々を捕えて煮て食うという話である。しかしその当時は何という考もなかったから別段恐しいとも思わなかった。ただ彼の掌に載せられてスーと持ち上げられた時何だかフワフワした感じがあったばかりである。掌の上で少し落ちついて書生の顔を見たのがいわゆる人間というものの見始であろう。この時妙なものだと思った感じが今でも残っている。第一毛をもって装飾されべきはずの顔がつるつるしてまるで薬缶だ。その後猫にもだいぶ逢ったがこんな片輪には一度も出会わした事がない。のみならず顔の真中があまりに突起している。そうしてその穴の中から時々ぷうぷうと煙を吹く。どうも咽せぽくて実に弱った。これが人間の飲む煙草というものである事はようやくこの頃知った。\r\n\u3000この書生の掌の裏でしばらくはよい心持に坐っておったが、しばらくすると非常な速力で運転し始めた。書生が動くのか自分だけが動くのか分らないが無暗に眼が廻る。胸が悪くなる。到底助からないと思っていると、どさりと音がして眼から火が出た。それまでは記憶しているがあとは何の事やらいくら考え出そうとしても分らない。\r\n\u3000ふと気が付いて見ると書生はいない。たくさんおった兄弟が一疋も見えぬ。肝心の母親さえ姿を隠してしまった。その上今までの所とは違って無暗に明るい。眼を明いていられぬくらいだ。はてな何でも容子がおかしいと、のそのそ這い出して見ると非常に痛い。吾輩は藁の上から急に笹原の中へ棄てられたのである。\r\n\u3000ようやくの思いで笹原を這い出すと向うに大きな池がある。吾輩は池の前に坐ってどうしたらよかろうと考えて見た。別にこれという分別も出ない。しばらくして泣いたら書生がまた迎に来てくれるかと考え付いた。ニャー、ニャーと試みにやって見たが誰も来ない。そのうち池の上をさらさらと風が渡って日が暮れかかる。腹が非常に減って来た。泣きたくても声が出ない。仕方がない、何でもよいから食物のある所まであるこうと決心をしてそろ

In [ ]:
import re

pattern = re.compile(r"\n一\n|\r\n|\n|\u3000", re.MULTILINE | re.DOTALL)

texts = re.sub(pattern, "", texts)

In [ ]:
from janome.tokenizer import Tokenizer
import jaconv

def get_yomigana(original_txt):
  t = Tokenizer()
  l = []
  for w in t.tokenize(original_txt):
    reading = w.reading
    if  reading == '*':
      l.append(w.base_form)
    else:
      l.append(reading)
  hira = jaconv.kata2hira(''.join(l))
  return hira

In [ ]:
get_yomigana("現在、気温が40度近くです。")

'げんざい、きおんが40どちかくです。'

# エンコーディング

## テキストを索引（インデックス）のリストに変換すること

* ユニークな文字を取得し、それぞれにインデックスを割り当てる

* 任意のテキストをエンコーディングする

* 吾輩は猫であるの文字種を取得し、それぞれにインデックスを割り当てる

* 吾輩は猫であるをエンコーディングする

In [ ]:
texts = get_yomigana(texts)

In [ ]:
def encode(txt):
  ctoi = {c:i for (i, c) in enumerate(sorted(set(texts)))}
  return [ctoi[c] for c in txt]
encoded_txt = encode(texts)

In [ ]:
encoded_txt

[126,
 60,
 95,
 53,
 95,
 93,
 67,
 87,
 51,
 123,
 44,
 90,
 110,
 56,
 95,
 110,
 80,
 90,
 53,
 44,
 89,
 67,
 87,
 54,
 110,
 124,
 79,
 59,
 88,
 128,
 88,
 65,
 128,
 88,
 54,
 60,
 84,
 59,
 92,
 44,
 90,
 91,
 87,
 114,
 54,
 73,
 64,
 121,
 53,
 72,
 113,
 72,
 113,
 71,
 79,
 88,
 67,
 125,
 87,
 91,
 115,
 131,
 91,
 115,
 131,
 90,
 53,
 86,
 53,
 79,
 67,
 88,
 80,
 65,
 95,
 61,
 58,
 63,
 71,
 86,
 53,
 123,
 44,
 126,
 60,
 95,
 53,
 95,
 67,
 67,
 87,
 95,
 72,
 113,
 86,
 91,
 128,
 66,
 128,
 88,
 53,
 54,
 114,
 94,
 127,
 111,
 79,
 44,
 71,
 59,
 114,
 51,
 88,
 87,
 61,
 63,
 88,
 77,
 124,
 95,
 71,
 119,
 75,
 53,
 88,
 53,
 54,
 91,
 128,
 66,
 128,
 81,
 117,
 54,
 87,
 53,
 81,
 96,
 128,
 89,
 54,
 51,
 63,
 90,
 71,
 117,
 78,
 63,
 87,
 51,
 83,
 79,
 77,
 54,
 80,
 44,
 67,
 94,
 71,
 119,
 75,
 53,
 88,
 53,
 54,
 94,
 95,
 88,
 61,
 89,
 61,
 126,
 124,
 126,
 124,
 127,
 88,
 121,
 56,
 86,
 91,
 86,
 63,
 54,
 88,
 53,
 54,
 95,
 90,
 71,
 87,
 51,


# デコーディング
## 索引(インデックス)から単語の列（もしくは文字列）に変換すること

In [ ]:
def decode(idx):
  itoc = {i:c for (i, c) in enumerate(sorted(set(texts)))}
  return ''.join([itoc[i] for i in idx])

decoded = decode(encoded_txt[:10])

In [ ]:
help("lambda")

Lambdas
*******

   lambda_expr ::= "lambda" [parameter_list] ":" expression

Lambda expressions (sometimes called lambda forms) are used to create
anonymous functions. The expression "lambda parameters: expression"
yields a function object.  The unnamed object behaves like a function
object defined with:

   def <lambda>(parameters):
       return expression

See section Function definitions for the syntax of parameter lists.
Note that functions created with lambda expressions cannot contain
statements or annotations.

Related help topics: FUNCTIONS



In [ ]:
help("lambda")

Lambdas
*******

   lambda_expr ::= "lambda" [parameter_list] ":" expression

Lambda expressions (sometimes called lambda forms) are used to create
anonymous functions. The expression "lambda parameters: expression"
yields a function object.  The unnamed object behaves like a function
object defined with:

   def <lambda>(parameters):
       return expression

See section Function definitions for the syntax of parameter lists.
Note that functions created with lambda expressions cannot contain
statements or annotations.

Related help topics: FUNCTIONS



In [ ]:
ctoi = {c:i for (i, c) in enumerate(sorted(set(texts)))}
itoc = {i:c for (i, c) in enumerate(sorted(set(texts)))}

In [ ]:
encode = lambda s:[ctoi[c] for c in s]
decode = lambda l:''.join([itoc[i] for i in l])

In [ ]:
decode(encode(texts[:10]))

'わがはいはねこである'

# 訓練データと検証データの作成（Pytorchのtensor型に変換してsplit）

In [ ]:
import torch

data = torch.tensor(encode(texts), dtype=torch.long)

In [ ]:
data.shape

torch.Size([395470])

In [ ]:
data[:50]

tensor([126,  60,  95,  53,  95,  93,  67,  87,  51, 123,  44,  90, 110,  56,
         95, 110,  80,  90,  53,  44,  89,  67,  87,  54, 110, 124,  79,  59,
         88, 128,  88,  65, 128,  88,  54,  60,  84,  59,  92,  44,  90,  91,
         87, 114,  54,  73,  64, 121,  53,  72])

In [ ]:
n = int(0.9 * len(data))
train_data = data[:n]
test_data = data[n:]

In [ ]:
print(len(train_data), len(test_data))

355923 39547


# 大規模言語モデル（LLM: Large Language Models）の本質

・次のトークン予測（今回は文字予測）タスク用データの準備

・GPUを使った訓練

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([126,  60,  95,  53,  95,  93,  67,  87,  51])

In [ ]:
x = train_data[:block_size+1]
y = train_data[1:block_size+1]

for t in range(block_size):
  context = x[:t+1]
  target = y[t].item() #pytorch tutorial
  print(f"入力：{context}, 出力:{target}")

入力：tensor([126]), 出力:60
入力：tensor([126,  60]), 出力:95
入力：tensor([126,  60,  95]), 出力:53
入力：tensor([126,  60,  95,  53]), 出力:95
入力：tensor([126,  60,  95,  53,  95]), 出力:93
入力：tensor([126,  60,  95,  53,  95,  93]), 出力:67
入力：tensor([126,  60,  95,  53,  95,  93,  67]), 出力:87
入力：tensor([126,  60,  95,  53,  95,  93,  67,  87]), 出力:51


In [ ]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
block_size = 8
batch_size = 4
torch.manual_seed(825)

In [ ]:
torch.randint(len(data) - block_size, (batch_size, ))

tensor([105183,  23016, 179976, 116576])

In [ ]:
torch.stack([torch.tensor([1,2,3]), torch.tensor([4,5,6])])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
def get_batch(split):
  """ ミニバッチを取得
    split(str): train or test
  """
  data = train_data if split == 'train' else test_data
  ix = torch.randint(len(data) - block_size, (batch_size, ))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x.to(device), y.to(device)

In [ ]:
xb, yb = get_batch('train')

In [ ]:
xb.shape

torch.Size([4, 8])

In [ ]:
yb.shape

torch.Size([4, 8])

In [ ]:
xb

tensor([[ 71,  61,  90, 121, 121, 128, 110,  88],
        [128,  94,  59, 128,  59,  63, 127,  88],
        [114, 108,  63, 127,  71, 119,  54,  61],
        [131,  88, 114,  81,  51,  66, 121, 124]], device='cuda:0')

In [ ]:
yb

tensor([[ 61,  90, 121, 121, 128, 110,  88,  53],
        [ 94,  59, 128,  59,  63, 127,  88,  83],
        [108,  63, 127,  71, 119,  54,  61, 119],
        [ 88, 114,  81,  51,  66, 121, 124,  79]], device='cuda:0')

# 最も単純な2-gramモデルを訓練

* nn.Moduleクラスを継承

In [ ]:
vocab_size = len(set(texts))
vocab_size

673

In [ ]:
vocab_size = len(set([i.item() for i in data]))
vocab_size

673

In [ ]:
data[:10]

tensor([126,  60,  95,  53,  95,  93,  67,  87,  51, 123])

In [ ]:
texts[:10]

'わがはいはねこである'

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [ ]:
class BigramLanguageModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size).to(device)

  def forward(self, idx, targets):
    logits = self.token_embedding_table(idx)
    return logits

In [ ]:
m = BigramLanguageModel(vocab_size)

In [ ]:
out = m(xb, yb)

In [ ]:
xb.shape

torch.Size([4, 8])

In [ ]:
out[0].shape

torch.Size([8, 673])

In [ ]:
out

tensor([[[-0.0238,  0.4836, -1.2794,  ..., -0.8560,  0.6900, -1.2224],
         [ 0.0098, -0.4977, -1.6767,  ...,  0.8834,  1.0018,  1.7431],
         [ 1.9313,  1.3786, -1.0101,  ...,  0.3446,  1.2663,  0.2734],
         ...,
         [-1.5288, -0.5065, -1.2861,  ..., -1.0272, -0.7021,  1.1295],
         [-0.5599,  0.2612, -1.7893,  ..., -0.3391,  0.0912,  0.4208],
         [ 1.9650, -0.8913,  0.5921,  ...,  0.3632,  0.2208, -0.8550]],

        [[-1.5288, -0.5065, -1.2861,  ..., -1.0272, -0.7021,  1.1295],
         [ 1.2050,  0.7333,  0.0316,  ..., -0.5102,  0.2448, -0.8419],
         [ 0.8267,  0.2788, -2.6456,  ..., -1.5758, -1.2271,  0.5149],
         ...,
         [ 0.5166, -0.0446,  0.9283,  ..., -1.3275,  1.5114,  0.8338],
         [-0.0405, -0.6578,  0.7340,  ...,  1.2118, -0.3390, -1.0983],
         [ 1.9650, -0.8913,  0.5921,  ...,  0.3632,  0.2208, -0.8550]],

        [[ 0.5672,  0.4672, -0.5015,  ...,  1.0559,  0.2809,  1.2613],
         [-1.5352,  0.7513, -1.1041,  ...,  0

In [ ]:
class BigramLanguageModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size).to(device)

  def forward(self, idx, targets=None):
    logits = self.token_embedding_table(idx)
    if targets is None:
      loss = None
    else:
      B, T, C = logits.shape
      logits = logits.view(-1, C)
      targets = targets.view(-1)
      loss = F.cross_entropy(logits, targets)
    return logits, loss

  def generate(self, idx, max_tokens):
    for _ in range(max_tokens):
      # 予測
      logits, loss = self(idx)
      # 最後のタイムステップ（文字）にフォーカス
      logits = logits[:, -1, :] # (B, C)
      probs = F.softmax(logits, dim=-1)
      idx_next = torch.multinomial(probs, num_samples=1)
      idx = torch.cat((idx, idx_next), dim=1)  # (B, T+1)
    return idx

In [ ]:
model = BigramLanguageModel(vocab_size)

In [ ]:
m = model.to(device)

In [ ]:
logits, loss = m(xb, yb)

In [ ]:
print(logits.shape)

torch.Size([32, 673])


In [ ]:
print(loss)

tensor(7.2310, device='cuda:0', grad_fn=<NllLossBackward0>)


In [ ]:
idx = torch.zeros((1, 1), dtype=torch.long).to(device)

In [ ]:
idx

tensor([[0]], device='cuda:0')

In [ ]:
(sorted(set(texts)))[0]

' '

In [ ]:
decode(m.generate(idx, max_tokens=10)[0].tolist())

' 談淋に這d箝客愧事政'

# 訓練コード

In [ ]:
max_iters = 20000
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size=32

In [ ]:
eval_iters = 200
@torch.no_grad()
def estimate_loss():
  out = {}
  m.eval()
  for split in ['train', 'test']:
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
      X, Y = get_batch(split)
      logits, loss = m(X, Y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  m.train()
  return out

In [ ]:
eval_interval = 300
for steps in range(max_iters):
  if steps % eval_interval == 0:
    losses = estimate_loss()
    print(f"step: {steps}, train_loss: {losses['train']:.4f}, test loss {losses['test']:.4f}")
  xb, yb = get_batch("train")
  logits, loss = m(xb, yb) #推論
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()
  if steps % 1000 == 0:
    print(loss)

step: 0, train_loss: 7.0100, test loss 6.9989
tensor(6.8862, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 300, train_loss: 6.6630, test loss 6.6591
step: 600, train_loss: 6.3391, test loss 6.3233
step: 900, train_loss: 6.0144, test loss 6.0115
tensor(5.8402, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 1200, train_loss: 5.7190, test loss 5.7221
step: 1500, train_loss: 5.4440, test loss 5.4560
step: 1800, train_loss: 5.2065, test loss 5.2191
tensor(5.0970, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 2100, train_loss: 4.9757, test loss 5.0008
step: 2400, train_loss: 4.7806, test loss 4.8013
step: 2700, train_loss: 4.6062, test loss 4.6253
step: 3000, train_loss: 4.4359, test loss 4.4631
tensor(4.3844, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 3300, train_loss: 4.3060, test loss 4.3313
step: 3600, train_loss: 4.1808, test loss 4.2062
step: 3900, train_loss: 4.0700, test loss 4.1007
tensor(4.1491, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 4200, train_lo

In [ ]:
decode(m.generate(idx, max_tokens=100)[0].tolist())

' 易倆事m痞忽度学きたくにからいたずかりもうぶんをとこんざしいろうしない。かにてきっていでこにしへでにんとから、て、けんかげんじまれれむかもおものでするべかえてもって、ひろいた。それだけのおうにがいるた'

In [ ]:
texts[9000:10000]

'はらのたしになるもんか」かれはだいにかんしゃくにさわったようすで、かんちくをそいだようなみみをしきりとぴくつかせてあららかにたちさった。わがはいがくるまやのくろとちきになったのはこれからである。そのごわがはいはたびたびくろとかいこうする。かいこうするごとにかれはくるまやそうとうのきえんをはく。さきにわがはいがみみにしたというふとくじけんもじつはくろからきいたのである。あるるひれいのごとくわがはいとくろはあたたかいちゃはたけのなかでねころびながらいろいろざつだんをしていると、かれはいつものじまんはなしをさもあたらしそうにくりかえしたあとで、わがはいにむかってしたのごとくしつもんした。「ごめえはいままでにねずみをなんひきとったことがある」ちしきはくろよりもよほどはったつしているつもりだがわんりょくとゆうきとにいたってはとうていくろのひかくにはならないとかくごはしていたものの、このといにせっしたるときは、さすがにきまりがよくはなかった。けれどもじじつはじじつで詐るわけにはいかないから、わがはいは「じつはとろうとろうとおもってまだとらない」とこたえた。くろはかれのはなのさきからぴんと突張っているながいひげをびりびりとふるわせてひじょうにわらった。がんらいくろはじまんをするたけにどこかたりないところがあって、かれのきえんをかんしんしたようにいんこうをころころならしてきんちょうしていればはなはだぎょしやすいねこである。わがはいはかれとこんづけになってからじかにこのこきゅうをのみこんだからこのばあいにもなまじいおのれれをべんごしてますますけいせいをわるくするのもぐである、いっそのことかれにじぶんのてがらばなしをしゃべらしてごちゃをにごすにわかくはないとしあんをさだめた。そこでおとなしく「きみなどはとしがとしであるからだいぶとったろう」とそそのかしてみた。かぜんかれは墻壁のけつしょにとっかんしてきた。「たんとでもねえがさんよんじゅうはとったろう」とはとくいげなるかれのこたえであった。かれはなおかたりをつづけて「ねずみのひゃくやにひゃくはいちにんでいつでもひきうけるがいたちってえやつはてにあわねえ。いちどいたちにむかってひどいめにあった」「へえなるほど」とあいづちをうつ。くろはおおきなめをぱちつかせていう。「きょねんのだいそうじのときだ。うちのていしゅがせっかいのふくろをもって椽の

# Self-Attentionの考え方
0. 言語モデルで現在のトークン（過去のトークンの平均）をfor文で単純に得る方法
1. 言語モデルで現在のトークンが持っている情報を効率的に得る方法 (attentionではない場合（平均））
2. Attention(Key, Query, Value)機構を効率的に得る方法

In [ ]:
import torch

torch.manual_seed(826)

B, T, C = 4, 8, 2
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 2])

わ→が→は→い→は→ね→こ→で→あ→る

In [ ]:
xbow = torch.zeros((B, T, C))
for b in range(B):
  for t in range(T):
    xprev = x[b, :t+1] # (t, C)
    xbow[b, t] = torch.mean(xprev, 0)
xbow[0]

tensor([[ 0.3604, -1.5006],
        [ 0.7338, -0.6960],
        [ 0.5539, -0.1388],
        [ 0.3351,  0.2609],
        [ 0.1492,  0.3077],
        [ 0.0892,  0.1931],
        [-0.0351,  0.1505],
        [ 0.0029,  0.3566]])

In [ ]:
o = torch.ones(3,3)
a = torch.tril(o)

In [ ]:
a = a / a.sum(1, keepdim=True)

In [ ]:
a

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])

In [ ]:
b = torch.randint(0, 10, (3,2)).float()
b

tensor([[8., 5.],
        [5., 0.],
        [7., 3.]])

In [ ]:
a@b

tensor([[8.0000, 5.0000],
        [6.5000, 2.5000],
        [6.6667, 2.6667]])

In [ ]:
o = torch.ones(T,T)
a = torch.tril(o)
w = a/ a.sum(1, keepdim=True)
xbow2 = w @ x

In [ ]:
xbow2[0]

tensor([[ 0.3604, -1.5006],
        [ 0.7338, -0.6960],
        [ 0.5539, -0.1388],
        [ 0.3351,  0.2609],
        [ 0.1492,  0.3077],
        [ 0.0892,  0.1931],
        [-0.0351,  0.1505],
        [ 0.0029,  0.3566]])

In [ ]:
xbow[0]

tensor([[ 0.3604, -1.5006],
        [ 0.7338, -0.6960],
        [ 0.5539, -0.1388],
        [ 0.3351,  0.2609],
        [ 0.1492,  0.3077],
        [ 0.0892,  0.1931],
        [-0.0351,  0.1505],
        [ 0.0029,  0.3566]])

In [ ]:
torch.allclose(xbow, xbow2)

True

In [ ]:
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

True

In [ ]:
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

# Self-Attention
* 単一ヘッドを持つアテンションの実装
* <u>すべての単語（文字）はその前までの単語（文字）の情報をデータによって変わる重みを考慮する</u>
* Query：何を探しているか、 Key: それぞれの単語（文字）が何の情報を持っているか、Value：最終出力対象の材料（ベクトルの基底）
→言い換えると、「Query（=問い合わせ）の各トークンに対応する、Value(=値)の重要度をKey（=鍵）を使って取り出し、Vの行ベクトルの線形結合として出力したもの」がSelf-Attentionである（参考：[Transformer: アテンションの計算式の意味を数理的に理解する](https://zenn.dev/bilzard/articles/49d453c7809be3)）

$$
Attention(Q, K, V) = softmax(\frac{QK^T}{\sqrt{d_k}})V
$$


In [ ]:
import torch
import torch.nn as nn

torch.manual_seed(827)

In [ ]:
B, T, C = 4, 8, 32
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 32])

In [ ]:
tril = torch.tril(torch.ones(T, T))
head_size = 16
query = nn.Linear(C, head_size, bias=False) # input: 32, output 16 -> 4, 8, 16
key = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

In [ ]:
q = query(x)
k = key(x)
v = value(x)

In [ ]:
q.shape

torch.Size([4, 8, 16])

In [ ]:
k.shape

torch.Size([4, 8, 16])

In [ ]:
k.transpose(-2, -1).shape

torch.Size([4, 16, 8])

In [ ]:
(q@k.transpose(-2, -1)).shape

torch.Size([4, 8, 8])

In [ ]:
d_k = head_size
import numpy as np

In [ ]:
d_k ** -0.5

0.25

In [ ]:
1/np.sqrt(d_k)

0.25

In [ ]:
wei = q@k.transpose(-2, -1) * (1/np.sqrt(d_k))
# wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=1)
xbow4 = wei @ v

In [ ]:
xbow4[0]

tensor([[-0.1200, -0.1601,  0.2589,  0.0208, -0.0648,  0.0027,  0.0125, -0.1319,
          0.1030,  0.1593,  0.0765,  0.1557, -0.0718,  0.0147, -0.2215,  0.0568],
        [-0.0108, -0.0218,  0.0766, -0.0081,  0.0053,  0.0279, -0.0353, -0.0339,
          0.0805,  0.0615,  0.0482,  0.0764, -0.0157, -0.0137, -0.1084,  0.0214],
        [ 0.2832,  0.2433,  0.1711, -0.1769,  0.2118,  0.3321, -0.3928,  0.1137,
          0.6217,  0.2233,  0.2119,  0.2911,  0.2739,  0.2648, -0.2952, -0.0544],
        [ 0.1207,  0.4009,  0.3361, -0.0288,  0.2656,  0.3648, -0.3785,  0.1752,
          0.4593, -0.0371,  0.1876, -0.2080,  0.3474,  0.5154, -0.2482,  0.0052],
        [ 0.0626,  0.4859,  0.1691, -0.0185,  0.1479,  0.3895, -0.4248,  0.1886,
          0.4691, -0.1431,  0.1500, -0.3176,  0.1735,  0.2553, -0.3713,  0.2097],
        [ 0.3021, -0.1055, -0.0995, -0.3695,  0.3832,  0.2057,  0.3904,  0.0583,
         -0.0238, -0.3994, -0.1742, -0.3680,  0.6366,  0.2916, -0.0166,  0.0525],
        [ 0.1683,  0.0

In [ ]:
torch.softmax(torch.tensor([0.1,-0.2,-0.3,-0.2,0.5]), dim=-1)

tensor([0.1919, 0.1408, 0.1274, 0.2565, 0.2835])

In [ ]:
torch.softmax(torch.tensor([0.1,-0.2,-0.3,-0.2,0.5])*8, dim=-1)

tensor([0.0388, 0.0035, 0.0016, 0.0035, 0.9525])

In [ ]:
q = torch.randn(B, T, d_k)
k =torch.randn(B, T, d_k)

In [ ]:
w = q @ k.transpose(-2,-1)*(1/np.sqrt(d_k))

In [ ]:
q.var()

tensor(0.9375)

In [ ]:
k.var()

tensor(1.0436)

In [ ]:
w.var()

tensor(1.0410)

# 全コード(改善後）

* positional encoding(まるごと体感したい、せとおおはし。 v.s. はしを使うのは難しい）
* MultiHead attention（Scaled dot product attentionを複数結合）
* dropoutを追加



# データ取得

In [ ]:
!pip install janome
!pip install jaconv

import requests, bs4
import re
from janome.tokenizer import Tokenizer
import jaconv
import torch

# よみがな（ひらがな）取得関数
def get_yomigana(original_txt):
  t = Tokenizer()
  l = []
  for w in t.tokenize(original_txt):
    reading = w.reading
    if  reading == '*':
      l.append(w.base_form)
    else:
      l.append(reading)
  hira = jaconv.kata2hira(''.join(l))
  return hira

# データ取得
response = requests.get("https://www.aozora.gr.jp/cards/000148/files/789_14547.html")
soup = bs4.BeautifulSoup(response.content, "html.parser")
elems = soup.select(".main_text")
texts = ''.join([elm.text for elm in elems])
pattern = re.compile(r"\n一\n|\r\n|\n|\u3000", re.MULTILINE | re.DOTALL)
texts = re.sub(pattern, "", texts)
texts = get_yomigana(texts)

# すべてのユニークな文字（夏目漱石の「吾輩は猫であるに出現）
chars = sorted(set(texts))
ctoi = {c:i for (i, c) in enumerate(chars)}
itoc = {i:c for (i, c) in enumerate(chars)}

# エンコーダ・デコーダの定義
encode = lambda s:[ctoi[c] for c in s]
decode = lambda l:''.join([itoc[i] for i in l])

# 訓練データ・検証用データの分け
data = torch.tensor(encode(texts), dtype=torch.long)
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

vocab_size = len(chars)

In [ ]:
vocab_size

673

# モデル定義　→　訓練　→　1件推論

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# 結果再現用
torch.manual_seed(827)

# ハイパーパラメタ
batch_size = 128 # いくつの独立したシーケンスを並列で扱うか
block_size = 128 # コンテキストサイズ（チャンクサイズwhat is the maximum context length for predictions?
max_iters = 1000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
# ------------

# ミニバッチ取得
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # 入力サイズ (batch_size, time-step, channels)
        # 出力しず (batch_size, time-step, head_size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,head_size)
        q = self.query(x) # (B,T,head_size)
        # アテンションスコアの計算("affinities:親和性")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, head_size) @ (B, head_size, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # 値の重みつき集約（値からアテンションスコアに基づき対応する成分を取り出す）の実行
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out

class MultiHeadAttention(nn.Module):
    """ 並行して計算可能なセルフアテンションヘッド """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ 非線形性をもつようにした全結合層 """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class GPTLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # 各トークンは、ルックアップテーブルから次のトークンのロジットを直接読み出す
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx：(B, T)
        for _ in range(max_new_tokens):
            # idxを最後のブロック・サイズ・トークンにクロップする。
            idx_cond = idx[:, -block_size:]
            # 推論
            logits, loss = self(idx_cond)
            # 最後のタイムステップのみに着目（言語モデルなので）
            logits = logits[:, -1, :] # becomes (B, C)
            # ソフトマックスを適用して確率を取得
            probs = F.softmax(logits, dim=-1) # (B, C)
            # 多項分布からサンプリング
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # シーケンスにサンプリングしたインデックスを追加
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = GPTLanguageModel()
m = model.to(device)
# モデルのパラメタ数を標準出力
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# 最適化関数は、AdamWを利用
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # eval_intervalの間隔ごとにlossの平均を評価する。
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, validation loss {losses['val']:.4f}")

    # ミニバッチを取得
    xb, yb = get_batch('train')

    # 誤差逆伝播
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# サンプルを生成してみる。
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))

11.207329 M parameters
step 0: train loss 6.4870, validation loss 6.4869
step 500: train loss 2.6419, validation loss 2.8797
step 999: train loss 2.0711, validation loss 2.7962
 はっけんしつするくらいだ。これをしらずにむかっておこらんのである。しゅうめいはちきんじょうのやくぶふかないしゅつのかひかってくれればだくのはかっしである。ぬぼといおおいのずからかぜをひくだすにかにているにふうふうちがこんだけしかわきのけっかところでない。ただどころのためにねをひらいたしのはなしをして、はなしをすることはまたようにおもって、うまれごとくべしようかすが、いっしのくそをあげきしまわりのなかへはたかくけた。かおのしむかいそうとひぐるものところはろんぶんよりもないとへいぜんぼえてきだしたてぁい！としょうじがつまらあけて「しはそれじゃきみのなかむろはくくびぐるが、ぼりのまんぼうさんみずをねむくのでは、みやむをえずいぶんだけのらいたりで、すこぶるはたね。ひまのそれからはんへんぞんぶつのくらいなこころぼそいおんがすました。ぷれーとすおさめしをてそんこ」「かまわんとするんさ。そばめしをぼくらそんすってるんだな」くさいくんはへびめしめしくっている。迷亭はまったそうだとおもいおおやこのこえがする。迷にっせぬとおりなげんのほうへまいぎわに。「ともえかにていしゃさけごのないへいにすまんまよんです
