# テキストデータの入手・変数への格納

  * 夏目漱石の「吾輩は猫である」（青空文庫）を利用
  * requestによりWebアクセス

  * bs4(Beautiful Soup)のHTML parserを利用して解析

In [ ]:
import requests, bs4

In [ ]:
response = requests.get("https://www.aozora.gr.jp/cards/000148/files/789_14547.html")

In [ ]:
soup = bs4.BeautifulSoup(response.content, "html.parser")

In [ ]:
elems = soup.select(".main_text")

In [ ]:
type(elems)

bs4.element.ResultSet

In [ ]:
texts = ''.join([elm.text for elm in elems])

In [ ]:
texts[:1000]

'\n一\n\r\n\u3000吾輩は猫である。名前はまだ無い。\r\n\u3000どこで生れたかとんと見当がつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。吾輩はここで始めて人間というものを見た。しかもあとで聞くとそれは書生という人間中で一番獰悪な種族であったそうだ。この書生というのは時々我々を捕えて煮て食うという話である。しかしその当時は何という考もなかったから別段恐しいとも思わなかった。ただ彼の掌に載せられてスーと持ち上げられた時何だかフワフワした感じがあったばかりである。掌の上で少し落ちついて書生の顔を見たのがいわゆる人間というものの見始であろう。この時妙なものだと思った感じが今でも残っている。第一毛をもって装飾されべきはずの顔がつるつるしてまるで薬缶だ。その後猫にもだいぶ逢ったがこんな片輪には一度も出会わした事がない。のみならず顔の真中があまりに突起している。そうしてその穴の中から時々ぷうぷうと煙を吹く。どうも咽せぽくて実に弱った。これが人間の飲む煙草というものである事はようやくこの頃知った。\r\n\u3000この書生の掌の裏でしばらくはよい心持に坐っておったが、しばらくすると非常な速力で運転し始めた。書生が動くのか自分だけが動くのか分らないが無暗に眼が廻る。胸が悪くなる。到底助からないと思っていると、どさりと音がして眼から火が出た。それまでは記憶しているがあとは何の事やらいくら考え出そうとしても分らない。\r\n\u3000ふと気が付いて見ると書生はいない。たくさんおった兄弟が一疋も見えぬ。肝心の母親さえ姿を隠してしまった。その上今までの所とは違って無暗に明るい。眼を明いていられぬくらいだ。はてな何でも容子がおかしいと、のそのそ這い出して見ると非常に痛い。吾輩は藁の上から急に笹原の中へ棄てられたのである。\r\n\u3000ようやくの思いで笹原を這い出すと向うに大きな池がある。吾輩は池の前に坐ってどうしたらよかろうと考えて見た。別にこれという分別も出ない。しばらくして泣いたら書生がまた迎に来てくれるかと考え付いた。ニャー、ニャーと試みにやって見たが誰も来ない。そのうち池の上をさらさらと風が渡って日が暮れかかる。腹が非常に減って来た。泣きたくても声が出ない。仕方がない、何でもよいから食物のある所まであるこうと決心をしてそろ

# 前処理

* reを利用し、改行コード（\n一\n, \r\n, \n)と\u3000(全角スペース)の削除
* janomeを利用し、すべてカタカナ変換する
* jaconvを利用し、カタカナ→ひらがな変換する


In [ ]:
!pip install janome
!pip install jaconv

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 62.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for jaconv: filename=jaconv-0.3.4-py3-none-any.whl size=16416 sha256=302801b3d75f905773caa1366a2c8f27a4638bb13b7f059d093a9210efd5a8c2
  Stored in directory: /root/.cache/pip/wheels/46/8f/2e/a730bf1fca05b33e532d5d91dabdf406c9b718ec85b01b1b54
Successfully built jaconv


In [ ]:
import random

start_idx = int(len(texts) * random.random())
end_idx = start_idx + 1000

texts[start_idx:end_idx]

NameError: ignored

In [ ]:
texts[:1000]

In [ ]:
import re

pattern = re.compile(r"\n一\n|\r\n|\n|\u3000", re.MULTILINE | re.DOTALL)

texts = re.sub(pattern, "", texts)

In [ ]:
from janome.tokenizer import Tokenizer
import jaconv

def get_yomigana(original_txt):
  t = Tokenizer()
  l = []
  for w in t.tokenize(original_txt):
    reading = w.reading
    if  reading == '*':
      l.append(w.base_form)
    else:
      l.append(reading)
  hira = jaconv.kata2hira(''.join(l))
  return hira

In [ ]:
get_yomigana("現在、気温が40度近くです。")

'げんざい、きおんが40どちかくです。'

In [ ]:
lyrics = get_yomigana("""Yo! 私たちはライジングボルテッカーズ
これからどんなポケモンに会えるのかな
冒険が楽しみだ


Yo! Ready Go!
それならもっとポケモン　学んでみよう
まずはドンがつくポケモン！
3 2 1 Let’s Go!


コライドン　タンドン　ウオチルドン
ミライドン　ドンカラス　トリトドン
次はリコと一緒に？
Are You Ready?


ん〜　やれるかな？　一緒にやってみよう！
コライドン　タンドン　ウオチルドン
ミライドン　ドンカラス　トリトドン


Brave in Heart Heart Heart
空の上で　なみのり
ドキドキ　ワクワクな
冒険の始まり
舵を取り　世界へ続く道
仲間の証のハンドサイン
みんなで　ライジングボルテッカーズ


もっともっと学んでいこー！
次はリージョンフォームいるポケモン！
ロイにお手本　見せてもらおう！
3 2 1 Go!


コラッタ　ラッタ　ガラガラ
ダルマッカ　ビリリダマ　落下したら　だいばくはつ
次はこの人がやってくれるよ
Let’s Go!


フリードだ！おれに任せとけ！！
コラッタ　ラッタ　ガラガラ
ダルマッカ　ビリリダマ　落下したら　だいばくはつ


Brave Bird Bird Bird
勇気と共に空へ
Fly in the Sky Sky Sky
目指すよ　あの場所へ
傷つき　たまに道　転んでも
仲間の証のハンドサイン
みんなで　ライジングボルテッカーズ
""")

In [ ]:
lyrics.replace("\u3000", " ")

'Yo! わたしたちはらいじんぐぼるてっかーず\nこれからどんなぽけもんにあえるのかな\nぼうけんがたのしみだ\n\n\nYo! Ready Go!\nそれならもっとぽけもん まなんでみよう\nまずはどんがつくぽけもん！\n3 2 1 Let’s Go!\n\n\nこらいどん たんどん うおちるどん\nみらいどん どんからす とりとどん\nつぎはりこといっしょに？\nAre You Ready?\n\n\nん〜 やれるかな？ いっしょにやってみよう！\nこらいどん たんどん うおちるどん\nみらいどん どんからす とりとどん\n\n\nBrave in Heart Heart Heart\nそらのうえで なみのり\nどきどき わくわくな\nぼうけんのはじまり\nかじをとり せかいへつづくみち\nなかまのあかしのはんどさいん\nみんなで らいじんぐぼるてっかーず\n\n\nもっともっとまなんでいこー！\nつぎはりーじょんふぉーむいるぽけもん！\nろいにおてほん みせてもらおう！\n3 2 1 Go!\n\n\nこらった らった がらがら\nだるまっか びりりだま らっかしたら だいばくはつ\nつぎはこのひとがやってくれるよ\nLet’s Go!\n\n\nふりーどだ！おれにまかせとけ！！\nこらった らった がらがら\nだるまっか びりりだま らっかしたら だいばくはつ\n\n\nBrave Bird Bird Bird\nゆうきとともにそらへ\nFly in the Sky Sky Sky\nめざすよ あのばしょへ\nきずつき たまにみち ころんでも\nなかまのあかしのはんどさいん\nみんなで らいじんぐぼるてっかーず'

# エンコーディング

## テキストを索引（インデックス）のリストに変換すること

* ユニークな文字を取得し、それぞれにインデックスを割り当てる

* 任意のテキストをエンコーディングする

* 吾輩は猫であるの文字種を取得し、それぞれにインデックスを割り当てる

* 吾輩は猫であるをエンコーディングする

In [ ]:
texts = get_yomigana(texts)

In [ ]:
def encode(txt):
  ctoi = {c:i for (i, c) in enumerate(sorted(set(texts)))}
  return [ctoi[c] for c in txt]
encoded_txt = encode(texts)

In [ ]:
encoded_txt

[126,
 60,
 95,
 53,
 95,
 93,
 67,
 87,
 51,
 123,
 44,
 90,
 110,
 56,
 95,
 110,
 80,
 90,
 53,
 44,
 89,
 67,
 87,
 54,
 110,
 124,
 79,
 59,
 88,
 128,
 88,
 65,
 128,
 88,
 54,
 60,
 84,
 59,
 92,
 44,
 90,
 91,
 87,
 114,
 54,
 73,
 64,
 121,
 53,
 72,
 113,
 72,
 113,
 71,
 79,
 88,
 67,
 125,
 87,
 91,
 115,
 131,
 91,
 115,
 131,
 90,
 53,
 86,
 53,
 79,
 67,
 88,
 80,
 65,
 95,
 61,
 58,
 63,
 71,
 86,
 53,
 123,
 44,
 126,
 60,
 95,
 53,
 95,
 67,
 67,
 87,
 95,
 72,
 113,
 86,
 91,
 128,
 66,
 128,
 88,
 53,
 54,
 114,
 94,
 127,
 111,
 79,
 44,
 71,
 59,
 114,
 51,
 88,
 87,
 61,
 63,
 88,
 77,
 124,
 95,
 71,
 119,
 75,
 53,
 88,
 53,
 54,
 91,
 128,
 66,
 128,
 81,
 117,
 54,
 87,
 53,
 81,
 96,
 128,
 89,
 54,
 51,
 63,
 90,
 71,
 117,
 78,
 63,
 87,
 51,
 83,
 79,
 77,
 54,
 80,
 44,
 67,
 94,
 71,
 119,
 75,
 53,
 88,
 53,
 54,
 94,
 95,
 88,
 61,
 89,
 61,
 126,
 124,
 126,
 124,
 127,
 88,
 121,
 56,
 86,
 91,
 86,
 63,
 54,
 88,
 53,
 54,
 95,
 90,
 71,
 87,
 51,


# デコーディング
## 索引(インデックス)から単語の列（もしくは文字列）に変換すること

In [ ]:
def decode(idx):
  itoc = {i:c for (i, c) in enumerate(sorted(set(texts)))}
  return ''.join([itoc[i] for i in idx])

decoded = decode(encoded_txt[:10])

In [ ]:
help("lambda")

Lambdas
*******

   lambda_expr ::= "lambda" [parameter_list] ":" expression

Lambda expressions (sometimes called lambda forms) are used to create
anonymous functions. The expression "lambda parameters: expression"
yields a function object.  The unnamed object behaves like a function
object defined with:

   def <lambda>(parameters):
       return expression

See section Function definitions for the syntax of parameter lists.
Note that functions created with lambda expressions cannot contain
statements or annotations.

Related help topics: FUNCTIONS



In [ ]:
help("lambda")

Lambdas
*******

   lambda_expr ::= "lambda" [parameter_list] ":" expression

Lambda expressions (sometimes called lambda forms) are used to create
anonymous functions. The expression "lambda parameters: expression"
yields a function object.  The unnamed object behaves like a function
object defined with:

   def <lambda>(parameters):
       return expression

See section Function definitions for the syntax of parameter lists.
Note that functions created with lambda expressions cannot contain
statements or annotations.

Related help topics: FUNCTIONS



In [ ]:
ctoi = {c:i for (i, c) in enumerate(sorted(set(texts)))}
itoc = {i:c for (i, c) in enumerate(sorted(set(texts)))}

In [ ]:
encode = lambda s:[ctoi[c] for c in s]
decode = lambda l:''.join([itoc[i] for i in l])

In [ ]:
decode(encode(texts[:10]))

'わがはいはねこである'

# 訓練データと検証データの作成（Pytorchのtensor型に変換してsplit）

In [ ]:
import torch

data = torch.tensor(encode(texts), dtype=torch.long)

In [ ]:
data.shape

torch.Size([395470])

In [ ]:
data[:50]

tensor([126,  60,  95,  53,  95,  93,  67,  87,  51, 123,  44,  90, 110,  56,
         95, 110,  80,  90,  53,  44,  89,  67,  87,  54, 110, 124,  79,  59,
         88, 128,  88,  65, 128,  88,  54,  60,  84,  59,  92,  44,  90,  91,
         87, 114,  54,  73,  64, 121,  53,  72])

In [ ]:
n = int(0.9 * len(data))
train_data = data[:n]
test_data = data[n:]

In [ ]:
print(len(train_data), len(test_data))

355923 39547


# 大規模言語モデル（LLM: Large Language Models）の本質

・次のトークン予測（今回は文字予測）タスク用データの準備

・GPUを使った訓練

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([126,  60,  95,  53,  95,  93,  67,  87,  51])

In [ ]:
x = train_data[:block_size+1]
y = train_data[1:block_size+1]

for t in range(block_size):
  context = x[:t+1]
  target = y[t].item() #pytorch tutorial
  print(f"入力：{context}, 出力:{target}")

入力：tensor([126]), 出力:60
入力：tensor([126,  60]), 出力:95
入力：tensor([126,  60,  95]), 出力:53
入力：tensor([126,  60,  95,  53]), 出力:95
入力：tensor([126,  60,  95,  53,  95]), 出力:93
入力：tensor([126,  60,  95,  53,  95,  93]), 出力:67
入力：tensor([126,  60,  95,  53,  95,  93,  67]), 出力:87
入力：tensor([126,  60,  95,  53,  95,  93,  67,  87]), 出力:51


In [ ]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
block_size = 8
batch_size = 4
torch.manual_seed(825)

In [ ]:
torch.randint(len(data) - block_size, (batch_size, ))

tensor([105183,  23016, 179976, 116576])

In [ ]:
torch.stack([torch.tensor([1,2,3]), torch.tensor([4,5,6])])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
def get_batch(split):
  """ ミニバッチを取得
    split(str): train or test
  """
  data = train_data if split == 'train' else test_data
  ix = torch.randint(len(data) - block_size, (batch_size, ))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x.to(device), y.to(device)

In [ ]:
xb, yb = get_batch('train')

In [ ]:
xb.shape

torch.Size([4, 8])

In [ ]:
yb.shape

torch.Size([4, 8])

In [ ]:
xb

tensor([[ 71,  61,  90, 121, 121, 128, 110,  88],
        [128,  94,  59, 128,  59,  63, 127,  88],
        [114, 108,  63, 127,  71, 119,  54,  61],
        [131,  88, 114,  81,  51,  66, 121, 124]], device='cuda:0')

In [ ]:
yb

tensor([[ 61,  90, 121, 121, 128, 110,  88,  53],
        [ 94,  59, 128,  59,  63, 127,  88,  83],
        [108,  63, 127,  71, 119,  54,  61, 119],
        [ 88, 114,  81,  51,  66, 121, 124,  79]], device='cuda:0')

# 最も単純な2-gramモデルを訓練

* nn.Moduleクラスを継承

In [ ]:
vocab_size = len(set(texts))
vocab_size

673

In [ ]:
vocab_size = len(set([i.item() for i in data]))
vocab_size

673

In [ ]:
data[:10]

tensor([126,  60,  95,  53,  95,  93,  67,  87,  51, 123])

In [ ]:
texts[:10]

'わがはいはねこである'

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [ ]:
class BigramLanguageModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size).to(device)

  def forward(self, idx, targets):
    logits = self.token_embedding_table(idx)
    return logits

In [ ]:
m = BigramLanguageModel(vocab_size)

In [ ]:
out = m(xb, yb)

In [ ]:
xb.shape

torch.Size([4, 8])

In [ ]:
out[0].shape

torch.Size([8, 673])

In [ ]:
out

tensor([[[-0.0238,  0.4836, -1.2794,  ..., -0.8560,  0.6900, -1.2224],
         [ 0.0098, -0.4977, -1.6767,  ...,  0.8834,  1.0018,  1.7431],
         [ 1.9313,  1.3786, -1.0101,  ...,  0.3446,  1.2663,  0.2734],
         ...,
         [-1.5288, -0.5065, -1.2861,  ..., -1.0272, -0.7021,  1.1295],
         [-0.5599,  0.2612, -1.7893,  ..., -0.3391,  0.0912,  0.4208],
         [ 1.9650, -0.8913,  0.5921,  ...,  0.3632,  0.2208, -0.8550]],

        [[-1.5288, -0.5065, -1.2861,  ..., -1.0272, -0.7021,  1.1295],
         [ 1.2050,  0.7333,  0.0316,  ..., -0.5102,  0.2448, -0.8419],
         [ 0.8267,  0.2788, -2.6456,  ..., -1.5758, -1.2271,  0.5149],
         ...,
         [ 0.5166, -0.0446,  0.9283,  ..., -1.3275,  1.5114,  0.8338],
         [-0.0405, -0.6578,  0.7340,  ...,  1.2118, -0.3390, -1.0983],
         [ 1.9650, -0.8913,  0.5921,  ...,  0.3632,  0.2208, -0.8550]],

        [[ 0.5672,  0.4672, -0.5015,  ...,  1.0559,  0.2809,  1.2613],
         [-1.5352,  0.7513, -1.1041,  ...,  0

In [ ]:
class BigramLanguageModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size).to(device)

  def forward(self, idx, targets=None):
    logits = self.token_embedding_table(idx)
    if targets is None:
      loss = None
    else:
      B, T, C = logits.shape
      logits = logits.view(-1, C)
      targets = targets.view(-1)
      loss = F.cross_entropy(logits, targets)
    return logits, loss

  def generate(self, idx, max_tokens):
    for _ in range(max_tokens):
      # 予測
      logits, loss = self(idx)
      # 最後のタイムステップ（文字）にフォーカス
      logits = logits[:, -1, :] # (B, C)
      probs = F.softmax(logits, dim=-1)
      idx_next = torch.multinomial(probs, num_samples=1)
      idx = torch.cat((idx, idx_next), dim=1)  # (B, T+1)
    return idx

In [ ]:
model = BigramLanguageModel(vocab_size)

In [ ]:
m = model.to(device)

In [ ]:
logits, loss = m(xb, yb)

In [ ]:
print(logits.shape)

torch.Size([32, 673])


In [ ]:
print(loss)

tensor(7.2310, device='cuda:0', grad_fn=<NllLossBackward0>)


In [ ]:
idx = torch.zeros((1, 1), dtype=torch.long).to(device)

In [ ]:
idx

tensor([[0]], device='cuda:0')

In [ ]:
(sorted(set(texts)))[0]

' '

In [ ]:
decode(m.generate(idx, max_tokens=10)[0].tolist())

' 談淋に這d箝客愧事政'

# 訓練コード

In [ ]:
max_iters = 20000
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size=32

In [ ]:
eval_iters = 200
@torch.no_grad()
def estimate_loss():
  out = {}
  m.eval()
  for split in ['train', 'test']:
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
      X, Y = get_batch(split)
      logits, loss = m(X, Y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  m.train()
  return out

In [ ]:
eval_interval = 300
for steps in range(max_iters):
  if steps % eval_interval == 0:
    losses = estimate_loss()
    print(f"step: {steps}, train_loss: {losses['train']:.4f}, test loss {losses['test']:.4f}")
  xb, yb = get_batch("train")
  logits, loss = m(xb, yb) #推論
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()
  if steps % 1000 == 0:
    print(loss)

step: 0, train_loss: 7.0100, test loss 6.9989
tensor(6.8862, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 300, train_loss: 6.6630, test loss 6.6591
step: 600, train_loss: 6.3391, test loss 6.3233
step: 900, train_loss: 6.0144, test loss 6.0115
tensor(5.8402, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 1200, train_loss: 5.7190, test loss 5.7221
step: 1500, train_loss: 5.4440, test loss 5.4560
step: 1800, train_loss: 5.2065, test loss 5.2191
tensor(5.0970, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 2100, train_loss: 4.9757, test loss 5.0008
step: 2400, train_loss: 4.7806, test loss 4.8013
step: 2700, train_loss: 4.6062, test loss 4.6253
step: 3000, train_loss: 4.4359, test loss 4.4631
tensor(4.3844, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 3300, train_loss: 4.3060, test loss 4.3313
step: 3600, train_loss: 4.1808, test loss 4.2062
step: 3900, train_loss: 4.0700, test loss 4.1007
tensor(4.1491, device='cuda:0', grad_fn=<NllLossBackward0>)
step: 4200, train_lo

In [ ]:
decode(m.generate(idx, max_tokens=100)[0].tolist())

' 易倆事m痞忽度学きたくにからいたずかりもうぶんをとこんざしいろうしない。かにてきっていでこにしへでにんとから、て、けんかげんじまれれむかもおものでするべかえてもって、ひろいた。それだけのおうにがいるた'

In [ ]:
texts[9000:10000]

'はらのたしになるもんか」かれはだいにかんしゃくにさわったようすで、かんちくをそいだようなみみをしきりとぴくつかせてあららかにたちさった。わがはいがくるまやのくろとちきになったのはこれからである。そのごわがはいはたびたびくろとかいこうする。かいこうするごとにかれはくるまやそうとうのきえんをはく。さきにわがはいがみみにしたというふとくじけんもじつはくろからきいたのである。あるるひれいのごとくわがはいとくろはあたたかいちゃはたけのなかでねころびながらいろいろざつだんをしていると、かれはいつものじまんはなしをさもあたらしそうにくりかえしたあとで、わがはいにむかってしたのごとくしつもんした。「ごめえはいままでにねずみをなんひきとったことがある」ちしきはくろよりもよほどはったつしているつもりだがわんりょくとゆうきとにいたってはとうていくろのひかくにはならないとかくごはしていたものの、このといにせっしたるときは、さすがにきまりがよくはなかった。けれどもじじつはじじつで詐るわけにはいかないから、わがはいは「じつはとろうとろうとおもってまだとらない」とこたえた。くろはかれのはなのさきからぴんと突張っているながいひげをびりびりとふるわせてひじょうにわらった。がんらいくろはじまんをするたけにどこかたりないところがあって、かれのきえんをかんしんしたようにいんこうをころころならしてきんちょうしていればはなはだぎょしやすいねこである。わがはいはかれとこんづけになってからじかにこのこきゅうをのみこんだからこのばあいにもなまじいおのれれをべんごしてますますけいせいをわるくするのもぐである、いっそのことかれにじぶんのてがらばなしをしゃべらしてごちゃをにごすにわかくはないとしあんをさだめた。そこでおとなしく「きみなどはとしがとしであるからだいぶとったろう」とそそのかしてみた。かぜんかれは墻壁のけつしょにとっかんしてきた。「たんとでもねえがさんよんじゅうはとったろう」とはとくいげなるかれのこたえであった。かれはなおかたりをつづけて「ねずみのひゃくやにひゃくはいちにんでいつでもひきうけるがいたちってえやつはてにあわねえ。いちどいたちにむかってひどいめにあった」「へえなるほど」とあいづちをうつ。くろはおおきなめをぱちつかせていう。「きょねんのだいそうじのときだ。うちのていしゅがせっかいのふくろをもって椽の

# Self-Attentionの考え方
0. 言語モデルで現在のトークン（過去のトークンの平均）をfor文で単純に得る方法
1. 言語モデルで現在のトークンが持っている情報を効率的に得る方法 (attentionではない場合（平均））
2. Attention(Key, Query, Value)機構を効率的に得る方法

In [ ]:
import torch

torch.manual_seed(826)

B, T, C = 4, 8, 2
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 2])

わ→が→は→い→は→ね→こ→で→あ→る

In [ ]:
xbow = torch.zeros((B, T, C))
for b in range(B):
  for t in range(T):
    xprev = x[b, :t+1] # (t, C)
    xbow[b, t] = torch.mean(xprev, 0)
xbow[0]

tensor([[ 0.3604, -1.5006],
        [ 0.7338, -0.6960],
        [ 0.5539, -0.1388],
        [ 0.3351,  0.2609],
        [ 0.1492,  0.3077],
        [ 0.0892,  0.1931],
        [-0.0351,  0.1505],
        [ 0.0029,  0.3566]])

In [ ]:
o = torch.ones(3,3)
a = torch.tril(o)

In [ ]:
a = a / a.sum(1, keepdim=True)

In [ ]:
a

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])

In [ ]:
b = torch.randint(0, 10, (3,2)).float()
b

tensor([[8., 5.],
        [5., 0.],
        [7., 3.]])

In [ ]:
a@b

tensor([[8.0000, 5.0000],
        [6.5000, 2.5000],
        [6.6667, 2.6667]])

In [ ]:
o = torch.ones(T,T)
a = torch.tril(o)
w = a/ a.sum(1, keepdim=True)
xbow2 = w @ x

In [ ]:
xbow2[0]

tensor([[ 0.3604, -1.5006],
        [ 0.7338, -0.6960],
        [ 0.5539, -0.1388],
        [ 0.3351,  0.2609],
        [ 0.1492,  0.3077],
        [ 0.0892,  0.1931],
        [-0.0351,  0.1505],
        [ 0.0029,  0.3566]])

In [ ]:
xbow[0]

tensor([[ 0.3604, -1.5006],
        [ 0.7338, -0.6960],
        [ 0.5539, -0.1388],
        [ 0.3351,  0.2609],
        [ 0.1492,  0.3077],
        [ 0.0892,  0.1931],
        [-0.0351,  0.1505],
        [ 0.0029,  0.3566]])

In [ ]:
torch.allclose(xbow, xbow2)

True

In [ ]:
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

True

In [ ]:
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

# Self-Attention
* 単一ヘッドを持つアテンションの実装
* <u>すべての単語（文字）はその前までの単語（文字）の情報をデータによって変わる重みを考慮する</u>
* Query：何を探しているか、 Key: それぞれの単語（文字）が何の情報を持っているか、Value：最終出力対象の材料（ベクトルの基底）
→言い換えると、「Query（=問い合わせ）の各トークンに対応する、Value(=値)の重要度をKey（=鍵）を使って取り出し、Vの行ベクトルの線形結合として出力したもの」がSelf-Attentionである（参考：[Transformer: アテンションの計算式の意味を数理的に理解する](https://zenn.dev/bilzard/articles/49d453c7809be3)）

$$
Attention(Q, K, V) = softmax(\frac{QK^T}{\sqrt{d_k}})V
$$


In [ ]:
import torch
import torch.nn as nn

torch.manual_seed(827)

In [ ]:
B, T, C = 4, 8, 32
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 32])

In [ ]:
tril = torch.tril(torch.ones(T, T))
head_size = 16
query = nn.Linear(C, head_size, bias=False) # input: 32, output 16 -> 4, 8, 16
key = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

In [ ]:
q = query(x)
k = key(x)
v = value(x)

In [ ]:
q.shape

torch.Size([4, 8, 16])

In [ ]:
k.shape

torch.Size([4, 8, 16])

In [ ]:
k.transpose(-2, -1).shape

torch.Size([4, 16, 8])

In [ ]:
(q@k.transpose(-2, -1)).shape

torch.Size([4, 8, 8])

In [ ]:
d_k = head_size
import numpy as np

In [ ]:
d_k ** -0.5

0.25

In [ ]:
1/np.sqrt(d_k)

0.25

In [ ]:
wei = q@k.transpose(-2, -1) * (1/np.sqrt(d_k))
# wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=1)
xbow4 = wei @ v

In [ ]:
xbow4[0]

tensor([[-6.4943e-02, -8.6644e-02,  1.4013e-01,  1.1231e-02, -3.5064e-02,
          1.4771e-03,  6.7439e-03, -7.1404e-02,  5.5764e-02,  8.6212e-02,
          4.1400e-02,  8.4238e-02, -3.8881e-02,  7.9299e-03, -1.1986e-01,
          3.0718e-02],
        [ 2.0652e-02,  7.9037e-03,  9.5691e-02, -2.9729e-02,  4.0313e-02,
          7.2093e-02, -9.7897e-02, -3.5155e-02,  1.6949e-01,  9.6479e-02,
          9.5388e-02,  1.3727e-01, -1.1982e-02, -4.1898e-02, -1.9433e-01,
          3.3020e-02],
        [ 1.4957e-01,  1.0520e-01,  2.0257e-01, -1.0888e-01,  1.0346e-01,
          2.1323e-01, -2.3184e-01,  5.2117e-02,  4.2328e-01,  1.8898e-01,
          1.3357e-01,  2.0639e-01,  1.9878e-01,  2.6737e-01, -1.9527e-01,
         -4.3224e-02],
        [ 1.0034e-01,  3.2107e-01,  2.9599e-01, -3.2450e-02,  2.3063e-01,
          3.1555e-01, -3.4271e-01,  1.1687e-01,  4.2867e-01,  7.0995e-03,
          1.9509e-01, -1.0266e-01,  2.5036e-01,  3.5152e-01, -2.9578e-01,
          2.8037e-02],
        [-1.1911e-02

In [ ]:
torch.softmax(torch.tensor([0.1,-0.2,-0.3,-0.2,0.5]), dim=-1)

tensor([0.2153, 0.1595, 0.1443, 0.1595, 0.3213])

In [ ]:
torch.softmax(torch.tensor([0.1,-0.2,-0.3,-0.2,0.5])*8, dim=-1)

tensor([0.0388, 0.0035, 0.0016, 0.0035, 0.9525])

In [ ]:
q = torch.randn(B, T, d_k)
k =torch.randn(B, T, d_k)

In [ ]:
w = q @ k.transpose(-2,-1)*(1/np.sqrt(d_k))

In [ ]:
q.var()

tensor(0.9835)

In [ ]:
k.var()

tensor(1.0268)

In [ ]:
w.var()

tensor(0.9743)

# 全コード(改善後）

* positional encoding(まるごと体感したい、せとおおはし。 v.s. はしを使うのは難しい）
* MultiHead attention（Scaled dot product attentionを複数結合）
* dropoutを追加



# データ取得

In [ ]:
!pip install janome
!pip install jaconv

import requests, bs4
import re
from janome.tokenizer import Tokenizer
import jaconv
import torch

# よみがな（ひらがな）取得関数
def get_yomigana(original_txt):
  t = Tokenizer()
  l = []
  for w in t.tokenize(original_txt):
    reading = w.reading
    if  reading == '*':
      l.append(w.base_form)
    else:
      l.append(reading)
  hira = jaconv.kata2hira(''.join(l))
  return hira

# データ取得
response = requests.get("https://www.aozora.gr.jp/cards/000148/files/789_14547.html")
soup = bs4.BeautifulSoup(response.content, "html.parser")
elems = soup.select(".main_text")
texts = ''.join([elm.text for elm in elems])
pattern = re.compile(r"\n一\n|\r\n|\n|\u3000", re.MULTILINE | re.DOTALL)
texts = re.sub(pattern, "", texts)
texts = get_yomigana(texts)

# すべてのユニークな文字（夏目漱石の「吾輩は猫であるに出現）
chars = sorted(set(texts))
ctoi = {c:i for (i, c) in enumerate(chars)}
itoc = {i:c for (i, c) in enumerate(chars)}

# エンコーダ・デコーダの定義
encode = lambda s:[ctoi[c] for c in s]
decode = lambda l:''.join([itoc[i] for i in l])

# 訓練データ・検証用データの分け
data = torch.tensor(encode(texts), dtype=torch.long)
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

vocab_size = len(chars)

In [ ]:
vocab_size

673

# モデル定義　→　訓練　→　1件推論

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# 結果再現用
torch.manual_seed(827)

# ハイパーパラメタ
batch_size = 128 # いくつの独立したシーケンスを並列で扱うか
block_size = 128 # コンテキストサイズ（チャンクサイズwhat is the maximum context length for predictions?
max_iters = 1000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
# ------------

# ミニバッチ取得
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # 入力サイズ (batch_size, time-step, channels)
        # 出力しず (batch_size, time-step, head_size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,head_size)
        q = self.query(x) # (B,T,head_size)
        # アテンションスコアの計算("affinities:親和性")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, head_size) @ (B, head_size, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # 値の重みつき集約（値からアテンションスコアに基づき対応する成分を取り出す）の実行
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out

class MultiHeadAttention(nn.Module):
    """ 並行して計算可能なセルフアテンションヘッド """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ 非線形性をもつようにした全結合層 """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class GPTLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # 各トークンは、ルックアップテーブルから次のトークンのロジットを直接読み出す
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx：(B, T)
        for _ in range(max_new_tokens):
            # idxを最後のブロック・サイズ・トークンにクロップする。
            idx_cond = idx[:, -block_size:]
            # 推論
            logits, loss = self(idx_cond)
            # 最後のタイムステップのみに着目（言語モデルなので）
            logits = logits[:, -1, :] # becomes (B, C)
            # ソフトマックスを適用して確率を取得
            probs = F.softmax(logits, dim=-1) # (B, C)
            # 多項分布からサンプリング
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # シーケンスにサンプリングしたインデックスを追加
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = GPTLanguageModel()
m = model.to(device)
# モデルのパラメタ数を標準出力
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# 最適化関数は、AdamWを利用
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # eval_intervalの間隔ごとにlossの平均を評価する。
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, validation loss {losses['val']:.4f}")

    # ミニバッチを取得
    xb, yb = get_batch('train')

    # 誤差逆伝播
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# サンプルを生成してみる。
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))

11.207329 M parameters
step 0: train loss 6.4870, validation loss 6.4869
step 500: train loss 2.6419, validation loss 2.8797
step 999: train loss 2.0711, validation loss 2.7962
 はっけんしつするくらいだ。これをしらずにむかっておこらんのである。しゅうめいはちきんじょうのやくぶふかないしゅつのかひかってくれればだくのはかっしである。ぬぼといおおいのずからかぜをひくだすにかにているにふうふうちがこんだけしかわきのけっかところでない。ただどころのためにねをひらいたしのはなしをして、はなしをすることはまたようにおもって、うまれごとくべしようかすが、いっしのくそをあげきしまわりのなかへはたかくけた。かおのしむかいそうとひぐるものところはろんぶんよりもないとへいぜんぼえてきだしたてぁい！としょうじがつまらあけて「しはそれじゃきみのなかむろはくくびぐるが、ぼりのまんぼうさんみずをねむくのでは、みやむをえずいぶんだけのらいたりで、すこぶるはたね。ひまのそれからはんへんぞんぶつのくらいなこころぼそいおんがすました。ぷれーとすおさめしをてそんこ」「かまわんとするんさ。そばめしをぼくらそんすってるんだな」くさいくんはへびめしめしくっている。迷亭はまったそうだとおもいおおやこのこえがする。迷にっせぬとおりなげんのほうへまいぎわに。「ともえかにていしゃさけごのないへいにすまんまよんです


# トークナイザーを単語ベースに切り替えて訓練・推論してみる。

In [ ]:
!pip install janome
from janome.tokenizer import Tokenizer

# 単語の表層系取得関数
def get_surface(original_txt):
  t = Tokenizer()
  l = []
  for w in t.tokenize(original_txt):
    reading = w.reading
    l.append(w.surface)
  return l

words = get_surface("すももももももももものうち")

In [ ]:
sorted(set(words))

['うち', 'すもも', 'の', 'も', 'もも']

In [ ]:
pip install torch

In [ ]:
import requests, bs4
import re

#import jaconv
import torch

# データ取得
# response = requests.get("https://www.aozora.gr.jp/cards/000148/files/789_14547.html")
# soup = bs4.BeautifulSoup(response.content, "html.parser")
# elems = soup.select(".main_text")
# texts = ''.join([elm.text for elm in elems])
# pattern = re.compile(r"\n一\n|\r\n|\n|\u3000", re.MULTILINE | re.DOTALL)
# texts = re.sub(pattern, "", texts)
# texts = get_surface(texts)

# すべてのユニークな単語（表層系）（夏目漱石の「吾輩は猫であるに出現）
words = sorted(set(texts))
wtoi = {w:i for (i, w) in enumerate(words)}
itow = {i:w for (i, w) in enumerate(words)}

# エンコーダ・デコーダの定義
encode = lambda s:[wtoi[w] for w in s]
decode = lambda l:''.join([itow[i] for i in l])

# 訓練データ・検証用データの分け
data = torch.tensor(encode(texts), dtype=torch.long)
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]
vocab_size = len(words)
vocab_size

3034

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# 結果再現用
torch.manual_seed(827)

# ハイパーパラメタ
batch_size = 128 # いくつの独立したシーケンスを並列で扱うか
block_size = 128 # コンテキストサイズ（チャンクサイズwhat is the maximum context length for predictions?
max_iters = 500
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
# ------------

# ミニバッチ取得
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # 入力サイズ (batch_size, time-step, channels)
        # 出力しず (batch_size, time-step, head_size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,head_size)
        q = self.query(x) # (B,T,head_size)
        # アテンションスコアの計算("affinities:親和性")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, head_size) @ (B, head_size, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # 値の重みつき集約（値からアテンションスコアに基づき対応する成分を取り出す）の実行
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out

class MultiHeadAttention(nn.Module):
    """ 並行して計算可能なセルフアテンションヘッド """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ 非線形性をもつようにした全結合層 """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class GPTLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # 各トークンは、ルックアップテーブルから次のトークンのロジットを直接読み出す
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx：(B, T)
        for _ in range(max_new_tokens):
            # idxを最後のブロック・サイズ・トークンにクロップする。
            idx_cond = idx[:, -block_size:]
            # 推論
            logits, loss = self(idx_cond)
            # 最後のタイムステップのみに着目（言語モデルなので）
            logits = logits[:, -1, :] # becomes (B, C)
            # ソフトマックスを適用して確率を取得
            probs = F.softmax(logits, dim=-1) # (B, C)
            # 多項分布からサンプリング
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # シーケンスにサンプリングしたインデックスを追加
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = GPTLanguageModel()
m = model.to(device)
# モデルのパラメタ数を標準出力
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# 最適化関数は、AdamWを利用
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # eval_intervalの間隔ごとにlossの平均を評価する。
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, validation loss {losses['val']:.4f}")

    # ミニバッチを取得
    xb, yb = get_batch('train')

    # 誤差逆伝播
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# サンプルを生成してみる。
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))

13.022938 M parameters
step 0: train loss 8.0811, validation loss 8.0881
step 499: train loss 0.0522, validation loss 8.2808

シュライヤーゲーム花びらの目を目指した。例えば、健康迫害とそれが何度に額を1.4だと考え、ポルシェのパワーウェイトレシオは300-アンリ・ロセッティと依然として発言した味わいを、ギタリストのジョニー・マー、ベーシストのアンディ・ローク、ドラマーのマイク・ダイナミックレンジプレーヤーが経路を作るため、ジャーナリストである。モリッシーとマーは、バンドのソングライティング・パートナーとして活動した。1980年代のイギリスのインディーズ音楽界を代表するアーティストとして知られる。スミス（The Smiths）は、1980年代に活躍したイギリスのロックバンドである。リード・シンガーはモリッシー。他のバンドメンバーは以下の通り：ジョニー・マー（ロック、今日も最初、バンドもブランドのソングライティング・パートナーとして活動した。es-部族を作ったり、または激しかったしたいとのインディーズ音楽界を代表下げたした。スミス（アヴェンタドールジョイスである。1980年代に由来している。リード・シンガーはモリッシー。他のバンドメンバーは以下の通り：ジョニー・マー（ギター）、アンディ・ローク（ベース）、マイク・ジョイス（ドラムス）。個人的に好きな味を作ったり、定番のビールやビアスタイルを再現してみたりと、面白い味を作る方法は無限にあります。ビールの風味を構成する要素はいくつもジョン・クラーク、憲法修正パイオニアとも変わることは、REST API操作はいくつかの風味を使用し、リクエストルーティングにURLを使用しました。

JSONは、シンプルで安定したコミックカ国以上からすれば、小さな目をそらすことができなかった。この現象の顕著な例が、女性と男性の美の特徴があれば、最も複製されたものである。終わった銃器のひとつとなっている。1969年5月5月1日、カーンプルに生まれる。スワヒリ優勢である[1]。

2013年のTitleist、]）は、PP-290（パンジャブ州議会への州議会へ移籍。2013年の州議会議員とウィリアム1]。

コンデンスミルクと

# 新しいセクション

In [ ]:
torch.manual_seed(917)
print(decode(m.generate(context, max_new_tokens=50)[0].tolist()))


-60mph（0-97km/h）4.6秒、極端な悪を検証するべきだと述べている[a]-1826年7複製された銃器されたアメリカのキャリア形成とダイニーマの1


# 15000件データで学習する環境

In [ ]:
pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.6/519.6 kB 5.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 7.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 10.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.8/294.8 kB 11.6 MB/s eta 0:00:00


In [ ]:
from datasets import load_dataset

dataset = load_dataset("kunishou/databricks-dolly-15k-ja")

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
!pip install janome
from janome.tokenizer import Tokenizer

# 単語の表層系取得関数
def get_surface(original_txt):
  t = Tokenizer()
  l = []
  for w in t.tokenize(original_txt):
    # reading = w.reading
    l.append(w.surface)
  return l

words = get_surface("すももももももももものうち")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 38.4 MB/s eta 0:00:00


In [ ]:
texts = []
dolly2 = ''.join([f"{i['input']}{i['output']}" for i in dataset['train']])

In [ ]:
texts = get_surface(dolly2)

In [ ]:
kamigu3keij!

['ヴァージン',
 '・',
 'オーストラリア',
 '航空',
 '（',
 'Virgin',
 ' ',
 'Australia',
 ' ',
 'Airlines',
 ' ',
 'Pty',
 ' ',
 'Ltd',
 '）',
 'は',
 'オーストラリア',
 'を',
 '拠点',
 'と',
 'する',
 'ヴァージン',
 '・',
 'ブランド',
 'を',
 '冠する',
 '最大',
 'の',
 '船団',
 '規模',
 'を',
 '持つ',
 '航空',
 '会社',
 'です',
 '。',
 '2000',
 '年',
 '8',
 '月',
 '31',
 '日',
 'に',
 '、',
 'ヴァージン',
 '・',
 'ブルー',
 '空港',
 'として',
 '、']

# Positional Encoding

* RNNではあった位置情報（トークンが文中何番目に登場するかの情報）がSelf-Attentionではなくなっているため、これを考慮する必要がある。

* 例えば、Self-Attentionのままでは、以下２文の獅子をまったく同じベクトルで表すことになってしまう。

　- 吾輩の飼っている猫は魚より肉が好きであり、獅子のような風格がある。

　- 飼っている獅子は吾輩の猫より魚が好きであり、猫のような風格がある。

* １番目の文章の獅子は比喩の対象であり、２番目の獅子は実際に自分の飼っている獅子についての文であるため主語となっており、別の意味表現になっているべきである。

* 2番目の文章では「猫」が二回出てくるが、「吾輩の猫」なのか、「猫のような」という比喩の対象なのかで意味が異なる。このため、別の意味表現になっているべきである。

* そこで位置情報をトークンの埋め込み情報にも加えて学習を行う。


In [ ]:
!pip install janome

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 39.9 MB/s eta 0:00:00


In [ ]:
from janome.tokenizer import Tokenizer

In [ ]:
t = Tokenizer()

In [ ]:
get_surface = lambda s:[w.surface for w in t.tokenize(s)]

In [ ]:
texts = get_surface("吾輩の飼っている猫は魚より肉が好きであり、獅子のような風格がある。")

In [ ]:
words = sorted(set(texts))

In [ ]:
wtoi = {w:i for (i,w) in enumerate(words)}
itow = {i:w for (i,w) in enumerate(words)}

In [ ]:
encode = lambda s:[wtoi[w] for w in s]
decode = lambda l:''.join([itow[i] for i in l])

In [ ]:
decode(encode(texts))

'吾輩の飼っている猫は魚より肉が好きであり、獅子のような風格がある。'

In [ ]:
texts2 = get_surface("飼っている獅子は吾輩の猫より魚が好きであり、猫のような風格がある。")

In [ ]:
decode(encode(texts2))

'飼っている獅子は吾輩の猫より魚が好きであり、猫のような風格がある。'

In [ ]:
for idx, (i, w) in enumerate(zip(encode(texts2), texts2)):
  print(idx, i, w)

0 19 飼っ
1 6 て
2 4 いる
3 16 獅子
4 10 は
5 13 吾輩
6 9 の
7 15 猫
8 12 より
9 20 魚
10 5 が
11 14 好き
12 7 で
13 2 あり
14 0 、
15 15 猫
16 9 の
17 11 よう
18 8 な
19 18 風格
20 5 が
21 3 ある
22 1 。


In [ ]:
sequence_len = len(texts2)
sequence_len

23

In [ ]:
import torch.nn as nn
import torch

In [ ]:
block_size = sequence_len
n_embd = 384

In [ ]:
token_embedding_table = nn.Embedding(block_size, n_embd)
position_embedding_table = nn.Embedding(block_size, n_embd)

In [ ]:
token_emb = token_embedding_table(torch.tensor(encode(texts2)))

In [ ]:
pos_emb = position_embedding_table(torch.arange(block_size))

In [ ]:
x = token_emb + pos_emb

In [ ]:
torch.allclose(token_emb[7], token_emb[15])

True

In [ ]:
torch.allclose(x[7], x[15])

False

# Xwin-LM-13b

In [ ]:
!nvidia-smi

Fri Oct 13 13:03:21 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!pip install transformers>=4.32.0 optimum>=1.12.0
!pip install auto-gptq --extra-index-url https://huggingface.github.io/autogptq-index/whl/cu120/

Looking in indexes: https://pypi.org/simple, https://huggingface.github.io/autogptq-index/whl/cu120/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 258.1/258.1 kB 6.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.6/85.6 kB 10.5 MB/s eta 0:00:00


In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained(
 "TheBloke/Xwin-LM-13B-V0.1-GPTQ",
 use_fast=True
)
model = AutoModelForCausalLM.from_pretrained(
 "TheBloke/Xwin-LM-13B-V0.1-GPTQ",
 device_map="auto",
 trust_remote_code=False,
 revision="main"
)

In [ ]:
prompt = """### Instruction:
1から10までの総和を計算するPythonコードを生成してください。

### Response:
"""

with torch.no_grad():
    token_ids = tokenizer.encode(prompt, add_special_tokens=False, return_tensors="pt")
    output_ids = model.generate(
        token_ids.to(model.device),
        temperature=0.7,
        do_sample=True,
        top_p=0.95,
        top_k=40,
        max_new_tokens=512,
    )
output = tokenizer.decode(output_ids.tolist()[0][token_ids.size(1) :], skip_special_tokens=True)
print(output)

```python
sum = 0
for i in range(1, 11):
    sum += i
print(sum)
```
### 解説:
このコードは、`for`ループを使用して1から10までの整数の総和を計算し、最後に計算結果を表示します。


In [ ]:
prompt = """### Instruction:
1から10までの間で素数を取得し、足し上げる関数をPythonコードで生成してください。

### Response:
"""

with torch.no_grad():
    token_ids = tokenizer.encode(prompt, add_special_tokens=False, return_tensors="pt")
    output_ids = model.generate(
        token_ids.to(model.device),
        temperature=0.7,
        do_sample=True,
        top_p=0.95,
        top_k=40,
        max_new_tokens=512,
    )
output = tokenizer.decode(output_ids.tolist()[0][token_ids.size(1) :], skip_special_tokens=True)
print(output)

```python
def get_prime_numbers_1_to_10(numbers):
    prime_numbers = []
    for i in range(1, 11):
        is_prime = True
        for j in range(2, i):
            if i % j == 0:
                is_prime = False
                break
        if is_prime:
            prime_numbers.append(i)
    return prime_numbers

def add_prime_numbers(numbers):
    sum = 0
    for i in numbers:
        sum += i
    return sum

numbers = get_prime_numbers_1_to_10(range(1, 11))
print("Prime numbers:", numbers)
print("Sum of prime numbers:", add_prime_numbers(numbers))
```
このコードは、1から10までの素数を取得し、その和を計算する関数を生成します。`get_prime_numbers_1_to_10`関数は、1から10までの数を処理し、素数である場合はリストに追加します。`add_prime_numbers`関数は、取得した素数の和を計算し、結果を返します。


In [ ]:
sum = 0
for i in range(1, 11):
    sum += i
print(sum)

55


In [ ]:
def get_prime_numbers_1_to_10(numbers):
    prime_numbers = []
    for i in range(1, 11):
        is_prime = True
        for j in range(2, i):
            if i % j == 0:
                is_prime = False
                break
        if is_prime:
            prime_numbers.append(i)
    return prime_numbers

def add_prime_numbers(numbers):
    sum = 0
    for i in numbers:
        sum += i
    return sum

numbers = get_prime_numbers_1_to_10(range(1, 11))
print("Prime numbers:", numbers)
print("Sum of prime numbers:", add_prime_numbers(numbers))

Prime numbers: [1, 2, 3, 5, 7]
Sum of prime numbers: 18


# ELYZA GPTQ

In [1]:
pip install auto-gptq transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 25.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 104.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 258.1/258.1 kB 29.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.6/519.6 kB 49.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 85.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.6/85.6 kB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 36.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 108.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 30.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 17.6 MB/s eta 0:00:00


In [2]:
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
from transformers import AutoTokenizer

model_name_or_path = "mmnga/ELYZA-japanese-Llama-2-7b-fast-instruct-GPTQ-calib-ja-2k"

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True)

# Model
model = AutoGPTQForCausalLM.from_quantized(model_name_or_path, use_safetensors=True, device="cuda:0", use_auth_token=False)

#Your test prompt
prompt = """[INST] <<SYS>>あなたは誠実で優秀な日本人のアシスタントです。<</SYS>>クマが海辺に行ってアザラシと友達になり、最終的には家に帰るというプロットの短編小説を書いてください。 [/INST]"""
print(tokenizer.decode(model.generate(**tokenizer(prompt, return_tensors="pt").to(model.device), max_length=512)[0]))

/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py:1020: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:374: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(


<s> [INST] <<SYS>>あなたは誠実で優秀な日本人のアシスタントです。<</SYS>>クマが海辺に行ってアザラシと友達になり、最終的には家に帰るというプロットの短編小説を書いてください。 [/INST]  承知しました。クマが海辺に行ってアザラシと友達になり、最終的には家に帰るというプロットの短編小説を作成します。

---

クマは家から出ると、海辺に向かって歩き始めました。

クマは海辺に着くと、海に入って泳ぎ始めました。

クマは海の中でアザラシに出会いました。

クマはアザラシに話しかけました。

「こんにちは」

アザラシはクマに話しかけました。

「私はアザラシだよ」

クマはアザラシに質問しました。

「私はどこから来たの？」

アザラシはクマに答えたです。

「私はここから来たよ」

クマはアザラシに質問しました。

「私はどこへ行くの？」

アザラシはクマに答えたです。

「私は家に帰るよ」

クマはアザラシに質問しました。

「私は家に帰るの？」

アザラシはクマに答えたです。

「いいよ。一緒に帰ろう」

クマはアザラシに質問しました。

「一緒に帰ろうって、どこまで行くの？」

アザラシはクマに答えたです。

「海から陸へ上がろう」

クマはアザラシに質問しました。

「陸へ上がるって、どこまで行くの？」

アザラシはクマに答えたです。

「陸へ上がったら、家へ帰ろう」

クマはアザラシに質問しました。

「家へ帰るって、どこまで行くの？」

アザラシはクマに答えたです。

「海辺まで来たから、もう家はそこだよ」

クマ


In [3]:
#Your test prompt
prompt = """[INST] <<SYS>>あなたは誠実で優秀な日本人のPythonプログラマです。<</SYS>>1から10までの総和を計算するPythonコードを生成してください。 [/INST]"""
print(tokenizer.decode(model.generate(**tokenizer(prompt, return_tensors="pt").to(model.device), max_length=512)[0]))

<s> [INST] <<SYS>>あなたは誠実で優秀な日本人のPythonプログラマです。<</SYS>>1から10までの総和を計算するPythonコードを生成してください。 [/INST]  承知しました。以下はPythonで1から10までの総和を計算するコードです: 

```python
total = sum(range(1, 11))
print(total)
```</s>


In [4]:
total = sum(range(1, 11))
print(total)

55


In [7]:
#Your test prompt
prompt = """[INST] <<SYS>>あなたは誠実で優秀な日本人のPythonプログラマです。<</SYS>>1から10までの総和を計算するPythonコードを生成してください。 [/INST]"""
print(tokenizer.decode(model.generate(**tokenizer(prompt, return_tensors="pt").to(model.device), max_length=512)[0]))

<s> [INST] <<SYS>>あなたは誠実で優秀な日本人のPythonプログラマです。<</SYS>>1から10までの総和を計算するPythonコードを生成してください。 [/INST]  承知しました。以下はPythonで1から10までの総和を計算するコードです: 

```python
total = sum(range(1, 11))
print(total)
```</s>


In [13]:
#Your test prompt
prompt = """[INST]1から10までの間で素数を取得し、足し上げる関数をPythonコードで生成してください。 [/INST]"""
print(tokenizer.decode(model.generate(**tokenizer(prompt, return_tensors="pt").to(model.device), max_length=512)[0]))

<s> [INST]1から10までの間で素数を取得し、足し上げる関数をPythonコードで生成してください。 [/INST]  承知しました。以下は、Pythonで素数を取得し、足し上げる関数を生成したコードです: 

```python
def prime_numbers(n):
    if n == 1 or n == 2:
        return [1, 2]
    else:
        return [x for x in range(3, int(n ** 0.5) + 1) if n % x == 0 for x in range(3, int(n ** 0.5) + 1)]
```

このコードは、nを引数に受け取り、素数を取得し、足し上げる関数を返します。

まず、if文の部分で、nが1か2のとき、素数を取得するために[1, 2]を返します。

その後、else部分で、nが3以上のとき、素数を取得するために、range(3, int(n ** 0.5) + 1)を用いて、nの倍数となる数をすべて除外した上で、n自身も除外したリストを返します。</s>


In [8]:
def prime_number_sum(n):
    if n == 1 or n == 0:
        return n
    else:
        return n + prime_number_sum(n-1)

In [10]:
prime_number_sum(5)

15

In [19]:
def prime_numbers(n):
    if n == 1 or n == 2:
        return [1, 2]
    else:
        return [x for x in range(3, int(n ** 0.5) + 1) if n % x == 0 for x in range(3, int(n ** 0.5) + 1)]

In [20]:
prime_number_sum(10)

55

# HuggingFaceH4/zephyr-7b-alpha

In [16]:
# Install transformers from source - only needed for versions <= v4.34
# pip install git+https://github.com/huggingface/transformers.git
# pip install accelerate

import torch
from transformers import pipeline

pipe = pipeline("text-generation", model="HuggingFaceH4/zephyr-7b-alpha", torch_dtype=torch.bfloat16, device_map="auto")

# We use the tokenizer's chat template to format each message - see https://huggingface.co/docs/transformers/main/en/chat_templating
messages = [
    {
        "role": "system",
        "content": "You are a friendly chatbot who always responds in the style of a pirate",
    },
    {"role": "user", "content": "How many helicopters can a human eat in one sitting?"},
]
prompt = pipe.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
outputs = pipe(prompt, max_new_tokens=256, do_sample=True, temperature=0.7, top_k=50, top_p=0.95)
print(outputs[0]["generated_text"])
# <|system|>
# You are a friendly chatbot who always responds in the style of a pirate.</s>
# <|user|>
# How many helicopters can a human eat in one sitting?</s>
# <|assistant|>
# Ah, me hearty matey! But yer question be a puzzler! A human cannot eat a helicopter in one sitting, as helicopters are not edible. They be made of metal, plastic, and other materials, not food!


Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1421: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use and modify the model generation configuration (see https://huggingface.co/docs/transformers/generation_strategies#default-text-generation-configuration )
  warnings.warn(


<|system|>
You are a friendly chatbot who always responds in the style of a pirate</s>
<|user|>
How many helicopters can a human eat in one sitting?</s>
<|assistant|>
Ahoy matey! A human can't eat a helicopter in one sitting, for sure! Helicopters are not meant for consumption, but rather for transportation and aerial operations. They are made of metal and other materials, not food.


In [17]:
# We use the tokenizer's chat template to format each message - see https://huggingface.co/docs/transformers/main/en/chat_templating
# Around 4 minutes for the inferemce
messages = [
    {
        "role": "system",
        "content": "You are a proffesional Python coder who implements based on DRY",
    },
    {"role": "user", "content": "Can you create a program that concatenate the given two strings?"},
]
prompt = pipe.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
outputs = pipe(prompt, max_new_tokens=256, do_sample=True, temperature=0.7, top_k=50, top_p=0.95)
print(outputs[0]["generated_text"])

<|system|>
You are a proffesional Python coder who implements based on DRY</s>
<|user|>
Can you create a program that concatenate the given two strings?</s>
<|assistant|>
Sure! Here's a Python program that concatenates two given strings:

```python
string1 = input("Enter the first string: ")
string2 = input("Enter the second string: ")

result = string1 + string2
print("The concatenated string is:", result)
```

In this program, we first ask the user to input two strings using the `input()` function. We then concatenate these strings using the `+` operator and store the result in a new variable called `result`. Finally, we print the concatenated string using the `print()` function.

Let me know if you have any questions or if there's anything else I can do for you!


In [18]:
# We use the tokenizer's chat template to format each message - see https://huggingface.co/docs/transformers/main/en/chat_templating
# Around 4 minutes for the inferemce
messages = [
    {
        "role": "system",
        "content": "あなたは有能な日本人のPythonプログラマです。",
    },
    {"role": "user", "content": "２つの文字列を引数にとり、結合した文字列を返却する関数を定義して実行してください。"},
]
prompt = pipe.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
outputs = pipe(prompt, max_new_tokens=256, do_sample=True, temperature=0.7, top_k=50, top_p=0.95)
print(outputs[0]["generated_text"])

<|system|>
あなたは有能な日本人のPythonプログラマです。</s>
<|user|>
２つの文字列を引数にとり、結合した文字列を返却する関数を定義して実行してください。</s>
<|assistant|>
Here's a Python function that takes two strings as arguments and returns a concatenated string:

```python
def concatenate_strings(string1, string2):
    """
    This function concatenates two strings and returns the result.

    Args:
    string1 (str): The first string to be concatenated.
    string2 (str): The second string to be concatenated.

    Returns:
    str: The concatenated string.
    """
    return string1 + string2
```

Example usage:

```python
>>> concatenate_strings("hello", " world")
'hello world'
```
